### ISSUE TITLE
Unsoundly mark `SyncVec::get_unchecked` as safe

### ISSUE THREAD

**Issue by safe4u** [darkrpc/dark-std#2]
Hi, thanks for your contribution to this repository first.

However, we have found a simple unsound problems in this crate:
The function [`get_unchecked`](https://github.com/darkrpc/dark-std/blob/f0cb6dd406548cb7ee3db92f3ba3d0cf847c1030/src/sync/vec.rs#L163) is wrongly marked as safe, which would confuse the boundary between safe and unsafe Rust.

We would appreciate your fix to this simple issue.

**Comment by zhuxiujia** [comment]
> Hi, thanks for your contribution to this repository first.
> 
> However, we have found a simple unsound problems in this crate: The function [`get_unchecked`](https://github.com/darkrpc/dark-std/blob/f0cb6dd406548cb7ee3db92f3ba3d0cf847c1030/src/sync/vec.rs#L163) is wrongly marked as safe, which would confuse the boundary between safe and unsafe Rust.
> 
> We would appreciate your fix to this simple issue.

Thank you for the reminder. I will correct this error
